### PR TITLE
publish installer container image

### LINKED ISSUE #71: Publish container image for installer
See quickstart guide which references a pre-built docker image to reduce quickstart install steps: https://www.substratus.ai/docs/quickstart

### PR DESCRIPTION
**Pull request by samos123**
Fixes #71

### CODE REVIEW

**Comment by nstogner** [comment]
LGTM

**Comment by samos123** [comment]
Chech the CI run here: https://github.com/substratusai/substratus/actions/runs/5479046949/jobs/9980344378?pr=74

**Comment by samos123** [comment]
don't forget to press the approve button

**Comment by samos123** [comment]
merging since Nick mentioned LGTM and want this as part of demo

**Pull request merged**
